Namespace Enums.Authentication
    Public Enum AuthResult As Byte
        WOW_SUCCESS = &H0
        WOW_FAIL_BANNED = &H3
        WOW_FAIL_UNKNOWN_ACCOUNT = &H4
        WOW_FAIL_INCORRECT_PASSWORD = &H5
        WOW_FAIL_ALREADY_ONLINE = &H6
        WOW_FAIL_NO_TIME = &H7
        WOW_FAIL_DB_BUSY = &H8
        WOW_FAIL_VERSION_INVALID = &H9
        WOW_FAIL_VERSION_UPDATE = &HA
        WOW_FAIL_INVALID_SERVER = &HB
        WOW_FAIL_SUSPENDED = &HC
        WOW_FAIL_FAIL_NOACCESS = &HD
        WOW_SUCCESS_SURVEY = &HE
        WOW_FAIL_PARENTCONTROL = &HF
        WOW_FAIL_LOCKED_ENFORCED = &H10
        WOW_FAIL_TRIAL_ENDED = &H11
        WOW_FAIL_ANTI_INDULGENCE = &H13
        WOW_FAIL_EXPIRED = &H14
        WOW_FAIL_NO_GAME_ACCOUNT = &H15
        WOW_FAIL_CHARGEBACK = &H16
        WOW_FAIL_GAME_ACCOUNT_LOCKED = &H18
        WOW_FAIL_UNLOCKABLE_LOCK = &H19
        WOW_FAIL_CONVERSION_REQUIRED = &H20
        WOW_FAIL_DISCONNECTED = &HFF
    End Enum
End NameSpace