Namespace Enums.Spell
    Public Enum SpellFailedReason As Byte
        SPELL_FAILED_AFFECTING_COMBAT = &H0                             ' 0x000
        SPELL_FAILED_ALREADY_AT_FULL_HEALTH = &H1                       ' 0x001
        SPELL_FAILED_ALREADY_AT_FULL_POWER = &H2                        ' 0x002
        SPELL_FAILED_ALREADY_BEING_TAMED = &H3                          ' 0x003
        SPELL_FAILED_ALREADY_HAVE_CHARM = &H4                           ' 0x004
        SPELL_FAILED_ALREADY_HAVE_SUMMON = &H5                          ' 0x005
        SPELL_FAILED_ALREADY_OPEN = &H6                                 ' 0x006
        'SPELL_FAILED_AURA_BOUNCED = &H7                                ' 0x007
        SPELL_FAILED_MORE_POWERFUL_SPELL_ACTIVE = &H7                   ' 0x007
        'SPELL_FAILED_AUTOTRACK_INTERRUPTED = &H8                       ' 0x008 ' old commented CAST_FAIL_FAILED = 8,-> 29
        SPELL_FAILED_BAD_IMPLICIT_TARGETS = &H9                         ' 0x009
        SPELL_FAILED_BAD_TARGETS = &HA                                  ' 0x00A
        SPELL_FAILED_CANT_BE_CHARMED = &HB                              ' 0x00B
        SPELL_FAILED_CANT_BE_DISENCHANTED = &HC                         ' 0x00C
        SPELL_FAILED_CANT_BE_PROSPECTED = &HD
        SPELL_FAILED_CANT_CAST_ON_TAPPED = &HE                          ' 0x00D
        SPELL_FAILED_CANT_DUEL_WHILE_INVISIBLE = &HF                    ' 0x00E
        SPELL_FAILED_CANT_DUEL_WHILE_STEALTHED = &H10                   ' 0x00F
        'SPELL_FAILED_CANT_STEALTH = &H10                               ' 0x010
        'SPELL_FAILED_CASTER_AURASTATE = &H11                           ' 0x011
        SPELL_FAILED_CANT_TOO_CLOSE_TO_ENEMY = &H11
        SPELL_FAILED_CANT_DO_THAT_YET = &H12
        SPELL_FAILED_CASTER_DEAD = &H13                                 ' 0x012
        SPELL_FAILED_CHARMED = &H14                                     ' 0x013
        SPELL_FAILED_CHEST_IN_USE = &H15                                ' 0x014
        SPELL_FAILED_CONFUSED = &H16                                    ' 0x015
        SPELL_FAILED_DONT_REPORT = &H17                                 ' 0x016 ' [-ZERO] need check
        SPELL_FAILED_EQUIPPED_ITEM = &H18                               ' 0x017
        SPELL_FAILED_EQUIPPED_ITEM_CLASS = &H19                         ' 0x018
        SPELL_FAILED_EQUIPPED_ITEM_CLASS_MAINHAND = &H1A                ' 0x019
        SPELL_FAILED_EQUIPPED_ITEM_CLASS_OFFHAND = &H1B                 ' 0x01A
        SPELL_FAILED_ERROR = &H1C                                       ' 0x01B
        SPELL_FAILED_FIZZLE = &H1D                                      ' 0x01C
        SPELL_FAILED_FLEEING = &H1E                                     ' 0x01D
        SPELL_FAILED_FOOD_LOWLEVEL = &H1F                               ' 0x01E
        SPELL_FAILED_HIGHLEVEL = &H20                                   ' 0x01F
        'SPELL_FAILED_HUNGER_SATIATED = &H21                            ' 0x020
        SPELL_FAILED_IMMUNE = &H22                                      ' 0x021
        SPELL_FAILED_INTERRUPTED = &H23                                 ' 0x022
        SPELL_FAILED_INTERRUPTED_COMBAT = &H24                          ' 0x023
        SPELL_FAILED_ITEM_ALREADY_ENCHANTED = &H25                      ' 0x024
        SPELL_FAILED_ITEM_GONE = &H26                                   ' 0x025
        SPELL_FAILED_ITEM_NOT_FOUND = &H27                              ' 0x026
        SPELL_FAILED_ITEM_NOT_READY = &H28                              ' 0x027
        SPELL_FAILED_LEVEL_REQUIREMENT = &H29                           ' 0x028
        SPELL_FAILED_LINE_OF_SIGHT = &H2A                               ' 0x029
        SPELL_FAILED_LOWLEVEL = &H2B                                    ' 0x02A
        SPELL_FAILED_LOW_CASTLEVEL = &H2C                               ' 0x02B
        SPELL_FAILED_MAINHAND_EMPTY = &H2D                              ' 0x02C
        SPELL_FAILED_MOVING = &H2E                                      ' 0x02D
        SPELL_FAILED_NEED_AMMO = &H2F                                   ' 0x02E
        SPELL_FAILED_NEED_REQUIRES_SOMETHING = &H30                     ' 0x02F
        SPELL_FAILED_NEED_EXOTIC_AMMO = &H31                            ' 0x030
        SPELL_FAILED_NOPATH = &H32                                      ' 0x031
        SPELL_FAILED_NOT_BEHIND = &H33                                  ' 0x032
        SPELL_FAILED_NOT_FISHABLE = &H34                                ' 0x033
        SPELL_FAILED_NOT_HERE = &H35                                    ' 0x034
        SPELL_FAILED_NOT_INFRONT = &H36                                 ' 0x035
        SPELL_FAILED_NOT_IN_CONTROL = &H37                              ' 0x036
        SPELL_FAILED_NOT_KNOWN = &H38                                   ' 0x037
        SPELL_FAILED_NOT_MOUNTED = &H39                                 ' 0x038
        SPELL_FAILED_NOT_ON_TAXI = &H3A                                 ' 0x039
        SPELL_FAILED_NOT_ON_TRANSPORT = &H3B                            ' 0x03A
        SPELL_FAILED_NOT_READY = &H3C                                   ' 0x03B
        SPELL_FAILED_NOT_SHAPESHIFT = &H3D                              ' 0x03C
        SPELL_FAILED_NOT_STANDING = &H3E                                ' 0x03D
        SPELL_FAILED_NOT_TRADEABLE = &H3F                               ' 0x03E ' rogues trying "enchant" other's weapon with poison
        SPELL_FAILED_NOT_TRADING = &H40                                 ' 0x03F ' CAST_FAIL_CANT_ENCHANT_TRADE_ITEM
        SPELL_FAILED_NOT_UNSHEATHED = &H41                              ' 0x040 ' yellow text
        SPELL_FAILED_NOT_WHILE_GHOST = &H42                             ' 0x041
        SPELL_FAILED_NO_AMMO = &H43                                     ' 0x042
        SPELL_FAILED_NO_CHARGES_REMAIN = &H44                           ' 0x043
        SPELL_FAILED_NO_CHAMPION = &H45                                 ' 0x044 ' CAST_FAIL_NOT_SELECT
        SPELL_FAILED_NO_COMBO_POINTS = &H46                             ' 0x045
        SPELL_FAILED_NO_DUELING = &H47                                  ' 0x046
        SPELL_FAILED_NO_ENDURANCE = &H48                                ' 0x047
        SPELL_FAILED_NO_FISH = &H49                                     ' 0x048
        SPELL_FAILED_NO_ITEMS_WHILE_SHAPESHIFTED = &H4A                 ' 0x049
        SPELL_FAILED_NO_MOUNTS_ALLOWED = &H4B                           ' 0x04A
        SPELL_FAILED_NO_PET = &H4C                                      ' 0x04B
        SPELL_FAILED_NO_POWER = &H4D                                    ' 0x04C ' CAST_FAIL_NOT_ENOUGH_MANA
        SPELL_FAILED_NOTHING_TO_DISPEL = &H4E                           ' 0x04D
        SPELL_FAILED_NOTHING_TO_STEAL = &H4F
        SPELL_FAILED_ONLY_ABOVEWATER = &H50                             ' 0x04E ' CAST_FAIL_CANT_USE_WHILE_SWIMMING
        SPELL_FAILED_ONLY_DAYTIME = &H51                                ' 0x04F
        SPELL_FAILED_ONLY_INDOORS = &H52                                ' 0x050
        SPELL_FAILED_ONLY_MOUNTED = &H53                                ' 0x051
        SPELL_FAILED_ONLY_NIGHTTIME = &H54                              ' 0x052
        SPELL_FAILED_ONLY_OUTDOORS = &H55                               ' 0x053
        SPELL_FAILED_ONLY_SHAPESHIFT = &H56                             ' 0x054
        SPELL_FAILED_ONLY_STEALTHED = &H57                              ' 0x055
        SPELL_FAILED_ONLY_UNDERWATER = &H58                             ' 0x056 ' CAST_FAIL_CAN_ONLY_USE_WHILE_SWIMMING
        SPELL_FAILED_OUT_OF_RANGE = &H59                                ' 0x057
        SPELL_FAILED_PACIFIED = &H5S                                    ' 0x058
        SPELL_FAILED_POSSESSED = &H5B                                   ' 0x059
        'SPELL_FAILED_REAGENTS = &H5C                                   ' 0x05A ' [-ZERO] not in 1.12
        SPELL_FAILED_REQUIRES_AREA = &H5D                               ' 0x05B ' CAST_FAIL_YOU_NEED_TO_BE_IN_XXX
        SPELL_FAILED_REQUIRES_SPELL_FOCUS = &H5E                        ' 0x05C ' CAST_FAIL_REQUIRES_XXX
        SPELL_FAILED_ROOTED = &H5F                                      ' 0x05D ' CAST_FAIL_UNABLE_TO_MOVE
        SPELL_FAILED_SILENCED = &H60                                    ' 0x05E
        SPELL_FAILED_SPELL_IN_PROGRESS = &H61                           ' 0x05F
        SPELL_FAILED_SPELL_LEARNED = &H62                               ' 0x060
        SPELL_FAILED_SPELL_UNAVAILABLE = &H63                           ' 0x061
        SPELL_FAILED_STUNNED = &H64                                     ' 0x062
        SPELL_FAILED_TARGETS_DEAD = &H65                                ' 0x063
        SPELL_FAILED_TARGET_AFFECTING_COMBAT = &H66                     ' 0x064
        SPELL_FAILED_TARGET_AURASTATE = &H67                            ' 0x065 ' CAST_FAIL_CANT_DO_THAT_YET_2
        SPELL_FAILED_TARGET_DUELING = &H68                              ' 0x066
        SPELL_FAILED_TARGET_ENEMY = &H69                                ' 0x067
        SPELL_FAILED_TARGET_ENRAGED = &H6A                              ' 0x068 ' CAST_FAIL_TARGET_IS_TOO_ENRAGED_TO_CHARM
        SPELL_FAILED_TARGET_FRIENDLY = &H6B                             ' 0x069
        SPELL_FAILED_TARGET_IN_COMBAT = &H6C                            ' 0x06A
        SPELL_FAILED_TARGET_IS_PLAYER = &H6D                            ' 0x06B
        SPELL_FAILED_TARGET_NOT_DEAD = &H6E                             ' 0x06C
        SPELL_FAILED_TARGET_NOT_IN_PARTY = &H6F                         ' 0x06D
        SPELL_FAILED_TARGET_NOT_LOOTED = &H70                           ' 0x06E ' CAST_FAIL_CREATURE_MUST_BE_LOOTED_FIRST
        SPELL_FAILED_TARGET_NOT_PLAYER = &H71                           ' 0x06F
        SPELL_FAILED_TARGET_NO_POCKETS = &H72                           ' 0x070 ' CAST_FAIL_NOT_ITEM_TO_STEAL
        SPELL_FAILED_TARGET_NO_WEAPONS = &H73                           ' 0x071
        SPELL_FAILED_TARGET_UNSKINNABLE = &H74                          ' 0x072
        SPELL_FAILED_THIRST_SATIATED = &H75                             ' 0x073
        SPELL_FAILED_TOO_CLOSE = &H76                                   ' 0x074
        SPELL_FAILED_TOO_MANY_OF_ITEM = &H77                            ' 0x075
        'SPELL_FAILED_TOTEMS = &H78                                     ' 0x076 ' [-ZERO] not in 1.12
        SPELL_FAILED_TRAINING_POINTS = &H79                             ' 0x077
        SPELL_FAILED_TRY_AGAIN = &H7A                                   ' 0x078 ' CAST_FAIL_FAILED_ATTEMPT
        SPELL_FAILED_UNIT_NOT_BEHIND = &H7B                             ' 0x079
        SPELL_FAILED_UNIT_NOT_INFRONT = &H7C                            ' 0x07A
        SPELL_FAILED_WRONG_PET_FOOD = &H7D                              ' 0x07B
        SPELL_FAILED_NOT_WHILE_FATIGUED = &H7E                          ' 0x07C
        SPELL_FAILED_TARGET_NOT_IN_INSTANCE = &H7F                      ' 0x07D ' CAST_FAIL_TARGET_MUST_BE_IN_THIS_INSTANCE
        SPELL_FAILED_NOT_WHILE_TRADING = &H80                           ' 0x07E
        SPELL_FAILED_TARGET_NOT_IN_RAID = &H81                          ' 0x07F
        SPELL_FAILED_DISENCHANT_WHILE_LOOTING = &H82                    ' 0x080
        SPELL_FAILED_PROSPECT_WHILE_LOOTING = &H83
        'SPELL_FAILED_PROSPECT_NEED_MORE = &H85
        SPELL_FAILED_TARGET_FREEFORALL = &H85                           ' 0x081
        SPELL_FAILED_NO_EDIBLE_CORPSES = &H86                           ' 0x082
        SPELL_FAILED_ONLY_BATTLEGROUNDS = &H87                          ' 0x083
        SPELL_FAILED_TARGET_NOT_GHOST = &H88                            ' 0x084
        SPELL_FAILED_TOO_MANY_SKILLS = &H89                             ' 0x085 ' CAST_FAIL_YOUR_PET_CANT_LEARN_MORE_SKILLS
        SPELL_FAILED_CANT_USE_NEW_ITEM = &H8A                           ' 0x086
        SPELL_FAILED_WRONG_WEATHER = &H8B                               ' 0x087 ' CAST_FAIL_CANT_DO_IN_THIS_WEATHER
        SPELL_FAILED_DAMAGE_IMMUNE = &H8C                               ' 0x088 ' CAST_FAIL_CANT_DO_IN_IMMUNE
        SPELL_FAILED_PREVENTED_BY_MECHANIC = &H8D                       ' 0x089 ' CAST_FAIL_CANT_DO_IN_XXX
        SPELL_FAILED_PLAY_TIME = &H8E                                   ' 0x08A ' CAST_FAIL_GAME_TIME_OVER
        SPELL_FAILED_REPUTATION = &H8F                                  ' 0x08B
        SPELL_FAILED_MIN_SKILL = &H90
        SPELL_FAILED_UNKNOWN = &H91                                     ' 0x08C
        SPELL_NO_ERROR = &HFF                                           ' 0x0FF
    End Enum
End NameSpace