Namespace Enums.Spell
    Public Enum SpellSchoolMask As Integer
        SPELL_SCHOOL_MASK_NONE = &H0
        SPELL_SCHOOL_MASK_NORMAL = &H1
        SPELL_SCHOOL_MASK_HOLY = &H2
        SPELL_SCHOOL_MASK_FIRE = &H4
        SPELL_SCHOOL_MASK_NATURE = &H8
        SPELL_SCHOOL_MASK_FROST = &H10
        SPELL_SCHOOL_MASK_SHADOW = &H20
        SPELL_SCHOOL_MASK_ARCANE = &H40
        SPELL_SCHOOL_MASK_SPELL = (SPELL_SCHOOL_MASK_FIRE Or SPELL_SCHOOL_MASK_NATURE Or SPELL_SCHOOL_MASK_FROST Or SPELL_SCHOOL_MASK_SHADOW Or SPELL_SCHOOL_MASK_ARCANE)
        SPELL_SCHOOL_MASK_MAGIC = (SPELL_SCHOOL_MASK_HOLY Or SPELL_SCHOOL_MASK_SPELL)
        SPELL_SCHOOL_MASK_ALL = (SPELL_SCHOOL_MASK_NORMAL Or SPELL_SCHOOL_MASK_MAGIC)
    End Enum
End NameSpace