Public Enum ObjectTypeID
    TYPEID_OBJECT = 0
    TYPEID_ITEM = 1
    TYPEID_CONTAINER = 2
    TYPEID_UNIT = 3
    TYPEID_PLAYER = 4
    TYPEID_GAMEOBJECT = 5
    TYPEID_DYNAMICOBJECT = 6
    TYPEID_CORPSE = 7
    TYPEID_AIGROUP = 8
    TYPEID_AREATRIGGER = 9
End Enum